version: '3'
services:
  couchdb:
    env_file:
      - env-couchdb.env
  backend:
    env_file:
      - env-backend.env
      - env-couchdb.env
    environment:
      - SERVER_NAME=${DOMAIN}
  celeryworker:
    env_file:
      - env-backend.env
      - env-couchdb.env
