[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "10.15.3"


[[redirects]]
  from = "/"
  to = "/us/"
  conditions = {Country = ["US"]}
  status = 200
  force = true

[[redirects]]
  from = "/create"
  to = "/us/create"
  conditions = {Country = ["US"]}
  status = 200
  force = true

[[redirects]]
  from = "/lolly/*"
  to = "/popsicle/:splat"
  conditions = {Country = ["US"]}
  status = 302
  force = true

# resolve the "new" URL to a function
[[redirects]]
  from = "/new"
  to = "/.netlify/functions/newLolly"
  status = 200

# unfound lollies should proxy to the API directly
[[redirects]]
  from = "/lolly/*"
  to = "/.netlify/functions/showLolly?id=:splat&lang=gb"
  status = 302
[[redirects]]
  from = "/popsicle/*"
  to = "/.netlify/functions/showLolly?id=:splat&lang=us"
  status = 302


# Not even available via the API? This really is a 404
[[redirects]]
  from = "/*"
  to = "/melted/index.html"
  force = false
  status = 404

[[redirects]]
  from = "/*"
  to = "/us/melted/index.html"
  conditions = {Country = ["US"]}
  force = false
  status = 404


# Use a Netlify Build plugin to enable incremental builds
[[plugins]]
  package = "./plugins/track-latest"

