name: ShareX
title: ShareX - The best free and open source screenshot tool for Windows
description: ShareX is a free and open source program that lets you capture or record any area of your screen and share it with a single press of a key. It also allows uploading images, text or other types of files to many supported destinations you can choose from.
url: https://getsharex.com
author: ShareX Team
github: https://github.com/ShareX/ShareX
twitter: GetShareX
googleAnalyticsId: UA-40712139-3
addThisId: 53e2d1c30114f995

encoding: utf-8
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM