version: '2'
services:
  coverage:
    build:
      context: .
      dockerfile: docker/Dockerfile.coverage

  test:
    build:
      context: .
      dockerfile: 'docker/Dockerfile.test'
    env_file:
      - ./.env.test
    volumes_from:
      - coverage
