version: '2'
services:
  db:
    image: postgres
    volumes:
      - .:/tmp/data/
  web:
    build: .
    image: graphql-django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
        - db